### ISSUE TITLE
No such file or directory: u'gtest/dependentlibs.list.gtest'

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/fuzzfetch#10]
fuzzfetch -d -a -n /build --tests common reftests gtest

[2017-09-06 23:05:22] Identified task: https://index.taskcluster.net/v1//task/gecko.v2.mozilla-central.latest.firefox.linux64-asan-debug
[2017-09-06 23:05:22] > Task ID: JWUeT0H2SyO5Jm7N_-BOug
[2017-09-06 23:05:22] > Rank: 1504719482
[2017-09-06 23:05:22] > Changeset: 93dd2e456c0ecca00fb4d28744e88078a77deaf7
[2017-09-06 23:05:22] > Build ID: 20170906173802
[2017-09-06 23:05:22] > Downloading and extracting archive: https://queue.taskcluster.net/v1/task/JWUeT0H2SyO5Jm7N_-BOug/artifacts/public/build/target.tar.bz2 ..
[2017-09-06 23:07:07] > Downloading and extracting archive: https://queue.taskcluster.net/v1/task/JWUeT0H2SyO5Jm7N_-BOug/artifacts/public/build/target.common.tests.zip ..
[2017-09-06 23:07:16] > Downloading and extracting archive: https://queue.taskcluster.net/v1/task/JWUeT0H2SyO5Jm7N_-BOug/artifacts/public/build/target.reftest.tests.zip ..
[2017-09-06 23:07:24] > Downloading and extracting archive: https://queue.taskcluster.net/v1/task/JWUeT0H2SyO5Jm7N_-BOug/artifacts/public/build/target.gtest.tests.zip ..
Traceback (most recent call last):
  File "/usr/local/bin/fuzzfetch", line 9, in <module>
    load_entry_point('fuzzfetch==0.5.3', 'console_scripts', 'fuzzfetch')()
  File "/usr/local/lib/python2.7/dist-packages/fuzzfetch/fetch.py", line 629, in main
    obj.extract_build(out_tmp, tests=extract_args['tests'], full_symbols=extract_args['full_symbols'])
  File "/usr/local/lib/python2.7/dist-packages/fuzzfetch/fetch.py", line 368, in extract_build
    os.path.join(path, 'dependentlibs.list.gtest'))
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'gtest/dependentlibs.list.gtest'

**Comment by kkuehl** [comment]
Re-ran and was successful:

/build/gtest$ ls d*
dash_dashinit.mp4  dependentlibs.list.gtest  downscaled.bmp  downscaled.gif  downscaled.ico  downscaled.icon  downscaled.jpg  downscaled.png

**Comment by kkuehl** [comment]
I am submitting a PR to fix.
