### ISSUE TITLE
Traceback due to incomplete download

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/fuzzfetch#16]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/code/fuzzfetch/src/fuzzfetch/__main__.py", line 9, in <module>
    Fetcher.main()
  File "/home/user/code/fuzzfetch/src/fuzzfetch/fetch.py", line 680, in main
    obj.extract_build(out_tmp, tests=extract_args['tests'], full_symbols=extract_args['full_symbols'])
  File "/home/user/code/fuzzfetch/src/fuzzfetch/fetch.py", line 377, in extract_build
    self.extract_tar(path)
  File "/home/user/code/fuzzfetch/src/fuzzfetch/fetch.py", line 513, in extract_tar
    for member in tar.getmembers():
  File "/usr/lib/python2.7/tarfile.py", line 1836, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib/python2.7/tarfile.py", line 2417, in _load
    tarinfo = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2348, in next
    self.fileobj.seek(self.offset - 1)
EOFError: compressed file ended before the logical end-of-stream was detected
```

**Comment by jschwartzentruber** [comment]
We can use requests-mock to add a test for this situation now. What is the expected behaviour? Print a better message and exit? Retry before failing?
