### ISSUE TITLE
MacOS Build download broken

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/fuzzfetch#45]
```
$ python -m fuzzfetch --fuzzing -a -o ~/workspace/browsers/
[2019-08-06 19:38:20] Identified task: https://index.taskcluster.net/v1/task/gecko.v2.mozilla-central.latest.firefox.macosx64-fuzzing-asan-opt
[2019-08-06 19:38:20] > Task ID: SXe6uN7XRKaS2y6UUNFLLg
[2019-08-06 19:38:20] > Rank: 1565127812
[2019-08-06 19:38:20] > Changeset: fb699b3c084c8d35e52f2b282de90ecb7b0992cd
[2019-08-06 19:38:20] > Build ID: 20190806214332
[2019-08-06 19:38:20] > Downloading: https://queue.taskcluster.net/v1/task/SXe6uN7XRKaS2y6UUNFLLg/artifacts/public/build/target.dmg (143.12MB total)
[2019-08-06 19:38:27] .. downloaded (18.66MB/s)
[2019-08-06 19:38:27] .. extracting
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/tsmith2/code/fuzzfetch/src/fuzzfetch/__main__.py", line 10, in <module>
    Fetcher.main()
  File "/Users/tsmith2/code/fuzzfetch/src/fuzzfetch/fetch.py", line 862, in main
    obj.extract_build(out, tests=extract_args['tests'], full_symbols=extract_args['full_symbols'])
  File "/Users/tsmith2/code/fuzzfetch/src/fuzzfetch/fetch.py", line 568, in extract_build
    self._write_fuzzmanagerconf(path)
  File "/Users/tsmith2/code/fuzzfetch/src/fuzzfetch/fetch.py", line 604, in _write_fuzzmanagerconf
    assert len(ff_loc) == 1
AssertionError
```

**Comment by jschwartzentruber** [comment]
Fixed in 13f300c39550451216506ed893d49573742696c2.
