### ISSUE TITLE
Python exception "ImportError: cannot import name ConverterMapping"

### ISSUE THREAD

**Issue by sylvestre** [MozillaSecurity/fuzzfetch#50]
Not a big deal but following the tutorial https://github.com/MozillaSecurity/grizzly/wiki/Getting-Started

I get:
```
% python2 -m fuzzfetch -a -n firefox --fuzzing -o $CODE/browsers/
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/home/sylvestre/dev/mozilla/fuzzfetch/src/fuzzfetch/__init__.py", line 7, in <module>
    from .fetch import *  # noqa pylint: disable=wildcard-import
  File "/home/sylvestre/dev/mozilla/fuzzfetch/src/fuzzfetch/fetch.py", line 28, in <module>
    import configparser  # pylint: disable=wrong-import-order
  File "/home/sylvestre/.local/lib/python2.7/site-packages/configparser.py", line 11, in <module>
    from backports.configparser import (
ImportError: cannot import name ConverterMapping
```
Removing the Debian package was enough to fix the issue
```
sudo apt remove python-configparser                            
```

(but remove flake8 too)

**Comment by jschwartzentruber** [comment]
This is because of the `python-configparser` version in Debian/Ubuntu. There is an Ubuntu [bug report][ubuntu-bug] for the issue. It was [fixed upstream][upstream-fix] in 3.5.1 or later.

[ubuntu-bug]: https://bugs.launchpad.net/ubuntu/+source/configparser/+bug/1821247
[upstream-fix]: https://github.com/jaraco/configparser/pull/22
